config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper do
    controllers tokens: "oauth/tokens"
  end

  namespace :simplecodingapi do
    post "/signup", to: 'signup#signup'
    post "/login", to: 'signin#login'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    invitations: "invitations",
    passwords: "passwords"
  }

  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    get "/articles", to: "simplecoding_articles#allarticles"
    get "/articles/:id", to: "simplecoding_articles#get_article_by_id"
    get "/articles/slugs/:slug", to: "simplecoding_articles#get_article_by_slug"
    get "/tags", to: "simplecoding_articles#tags"
    get "/tags/:tag", to: "simplecoding_articles#get_by_tag"
    get "/confirm-email", to: "devise/confirmations#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  scope "(/locale/:locale)", defaults: { locale: nil } do
    get "/locale/:locale" => "stories#index"
    require "sidekiq/web"
    require "sidekiq_unique_jobs/web"
    require "sidekiq/cron/web"

    authenticated :user, ->(user) { user.tech_admin? } do
      Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
      Sidekiq::Web.set :sessions, Rails.application.config.session_options
      Sidekiq::Web.class_eval do
        use Rack::Protection, permitted_origins: [URL.url] # resolve Rack Protection HttpOrigin
      end
      mount Sidekiq::Web => "/sidekiq"
      mount FieldTest::Engine, at: "abtests"
    end

    namespace :admin do
      get "/" => "admin_portals#index"

      authenticate :user, ->(user) { user.tech_admin? } do
        mount Blazer::Engine, at: "blazer"

        flipper_ui = Flipper::UI.app(Flipper,
                                     { rack_protection: { except: %i[authenticity_token form_token json_csrf
                                                                     remote_token http_origin session_hijacking] } })
        mount flipper_ui, at: "feature_flags"

        resources :data_update_scripts, only: [:index]
      end

      namespace :users do
        resources :gdpr_delete_requests, only: %i[index destroy]
      end

      resources :articles, only: %i[index show update]
      resources :broadcasts
      resources :buffer_updates, only: %i[create update]
      resources :listings, only: %i[index edit update destroy]
      resources :listing_categories, only: %i[index edit update new create
                                              destroy], path: "listings/categories"

      resources :comments, only: [:index]
      resources :events, only: %i[index create update new edit]
      resources :feedback_messages, only: %i[index show]
      resources :invitations, only: %i[index new create destroy]
      resources :pages, only: %i[index new create edit update destroy]
      resources :mods, only: %i[index update]
      resources :moderator_actions, only: %i[index]
      resources :navigation_links, only: %i[index update create destroy]
      resources :privileged_reactions, only: %i[index]
      resources :permissions, only: %i[index]
      resources :podcasts, only: %i[index edit update destroy] do
        member do
          post :fetch
          post :add_owner
        end
      end

      constraints(->(_request) { FeatureFlag.enabled?(:profile_admin) }) do
        resources :profile_field_groups, only: %i[update create destroy]
        resources :profile_fields, only: %i[index update create destroy]
      end
      resources :reactions, only: [:update]
      resources :response_templates, only: %i[index new edit create update destroy]
      resources :chat_channels, only: %i[index create update destroy] do
        member do
          delete :remove_user
        end
      end
      resources :reports, only: %i[index show], controller: "feedback_messages" do
        collection do
          post "send_email"
          post "create_note"
          post "save_status"
        end
      end
      resources :tags, only: %i[index new create update edit] do
        resource :moderator, only: %i[create destroy], module: "tags"
      end
      resources :users, only: %i[index show edit update] do
        resources :email_messages, only: :show

        member do
          post "banish"
          post "export_data"
          post "full_delete"
          patch "user_status"
          post "merge"
          delete "remove_identity"
          post "send_email"
          post "verify_email_ownership"
          patch "unlock_access"
        end
      end
      resources :organization_memberships, only: %i[update destroy create]
      resources :organizations, only: %i[index show] do
        member do
          patch "update_org_credits"
        end
      end
      resources :sponsorships, only: %i[index edit update new create destroy]
      resources :welcome, only: %i[index create]
      resources :growth, only: %i[index]
      resources :tools, only: %i[index create] do
        collection do
          post "bust_cache"
        end
      end
      resources :webhook_endpoints, only: :index
      resource :config
      resources :badges, only: %i[index edit update new create]
      resources :display_ads, only: %i[index edit update new create destroy]

      resources :html_variants, only: %i[index edit update new create show destroy]
      get "/badges/badge_achievements", to: redirect("/admin/badge_achievements")
      get "/badges/badge_achievements/award_badges", to: redirect("/admin/badge_achievements/award_badges")
      resources :badge_achievements, only: %i[index destroy]
      get "/badge_achievements/award_badges", to: "badge_achievements#award"
      post "/badge_achievements/award_badges", to: "badge_achievements#award_badges"
      resources :secrets, only: %i[index]
      put "secrets", to: "secrets#update"
    end

    namespace :stories, defaults: { format: "json" } do
      resource :feed, only: [:show] do
        get ":timeframe" => "feeds#show"
      end
    end

    namespace :api, defaults: { format: "json" } do
      scope module: :v0,
            constraints: ApiConstraints.new(version: 0, default: true) do
        resources :articles, only: %i[index show create update] do
          collection do
            get "me(/:status)", to: "articles#me", as: :me, constraints: { status: /published|unpublished|all/ }
            get "/:username/:slug", to: "articles#show_by_slug", as: :slug
          end
        end
        resources :comments, only: %i[index show]
        resources :videos, only: [:index]
        resources :podcast_episodes, only: [:index]
        resources :users, only: %i[show] do
          collection do
            get :me
          end
        end
        resources :tags, only: [:index]
        resources :follows, only: [:create] do
          collection do
            get :tags
          end
        end
        namespace :followers do
          get :users
          get :organizations
        end
        resources :readinglist, only: [:index]
        resources :webhooks, only: %i[index create show destroy]

        resources :listings, only: %i[index show create update]
        get "/listings/category/:category", to: "listings#index", as: :listings_category
        get "/analytics/totals", to: "analytics#totals"
        get "/analytics/historical", to: "analytics#historical"
        get "/analytics/past_day", to: "analytics#past_day"
        get "/analytics/referrers", to: "analytics#referrers"

        resources :health_checks, only: [] do
          collection do
            get :app
            get :search
            get :database
            get :cache
          end
        end

        resources :profile_images, only: %i[show], param: :username
        resources :organizations, only: [:show], param: :username do
          resources :users, only: [:index], to: "organizations#users"
          resources :listings, only: [:index], to: "organizations#listings"
          resources :articles, only: [:index], to: "organizations#articles"
        end

        namespace :admin do
          resource :config, only: %i[show update], defaults: { format: :json }
        end
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :chat_channels, only: %i[index show create update]
    resources :chat_channel_memberships, only: %i[index create edit update destroy]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } # internal API
    resources :users, only: %i[update]
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :followed_articles, only: [:index]
    resources :follows, only: %i[show create] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"

app/models/ahoy/event.rb
module Ahoy
  class Event < ApplicationRecord
    include Ahoy::QueryMethods

    self.table_name = "ahoy_events"

    belongs_to :visit
    belongs_to :user, optional: true
  end
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :cover_image, CoverImageUploader
  mount_uploader :profile_image, ProfileImageUploader

  validates :title, length: { maximum: 90 }
  validates :location_url, url: { allow_blank: true, schemes: %w[https http] }
  validate :end_time_after_start
  validates :slug, presence: { if: :published? }, format: /\A[0-9a-z-]*\z/
  before_validation :evaluate_markdown
  before_validation :create_slug
  after_save :bust_cache

  scope :in_the_future_and_published, lambda {
    where("starts_at > ?", Time.current)
      .where(published: true)
  }

  scope :in_the_past_and_published, lambda {
    where("starts_at < ?", Time.current)
      .where(published: true)
  }

  private

  def evaluate_markdown
    self.description_html = MarkdownProcessor::Parser.new(description_markdown).evaluate_markdown
  end

  def end_time_after_start
    if ends_at.nil? || starts_at.nil?
      errors.add(:starts_at, "and ends_at must not be nil")
    elsif ends_at < starts_at
      errors.add(:ends_at, "must be after start date")
    end
  end

  def create_slug
    self.slug = title_to_slug if slug.blank? && title.present? && published
  end

  def title_to_slug
    downcase = "#{id}-#{category}-#{title}"
    "#{downcase.parameterize}-#{starts_at.strftime('%m-%d-%Y')}"
  end

  def bust_cache
    Events::BustCacheWorker.perform_async
  end
end

app/models/webhook/event.rb
module Webhook
  class Event
    EVENT_TYPES = %w[
      article_created
      article_updated
      article_destroyed
    ].freeze

    attr_reader :event_type, :payload, :timestamp, :event_id

    def initialize(event_type:, payload: {})
      raise InvalidEvent unless EVENT_TYPES.include?(event_type)

      @event_type = event_type
      @payload = payload

      now = Time.current
      @timestamp = now.rfc3339
      @event_id = Secrets::Generator.sortable(now)
    end

    def as_json(*_args)
      Webhook::EventSerializer.new(self).serializable_hash
    end
  end

  class InvalidEvent < StandardError; end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < ApplicationController
    layout "admin"
    include ApplicationHelper

    def index
      @events = Event.order(starts_at: :desc).page(params[:page]).per(20)
    end

    def new
      @event = Event.new(
        location_name: "#{URL.domain}/live",
        location_url: app_url,
        description_markdown: "*Description* *Pre-requisites:* *Bio*",
      )
    end

    def edit
      @event = Event.find(params[:id])
    end

    def create
      @event = Event.new(event_params)
      if @event.save
        flash[:success] = "Successfully created event: #{@event.title}"
        redirect_to admin_events_path
      else
        flash[:danger] = @event.errors.full_messages
        render new_admin_event_path
      end
    end

    def update
      @event = Event.find(params[:id])
      if @event.update(event_params)
        flash[:success] = "#{@event.title} was successfully updated"
        redirect_to admin_events_path
      else
        flash[:danger] = @event.errors.full_messages
        render :edit
      end
    end

    private

    def event_params
      allowed_params = %i[
        title category event_date starts_at ends_at
        location_name cover_image location_url description_markdown published
        host_name profile_image live_now
      ]
      params.require(:event).permit(allowed_params)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_cache_control_headers, only: [:index]
  # No authorization required for entirely public controller

  def index
    @events = Event.in_the_future_and_published.sort_by(&:starts_at)
    @past_events = Event.in_the_past_and_published.sort_by(&:starts_at)
    set_surrogate_key_header "events_index_page"
    @past_events.reverse!
  end

  def show
    @event = Event.find_by!(slug: params[:id])
  end
end

app/views/admin/events/_event_form.html.erb
<div class="crayons-card p-6">
  <%= form_for [:admin, @event] do |f| %>
    <div class="crayons-field">
      <%= f.label :cover_image, class: "crayons-field__label" %>
      <%= f.file_field :cover_image, class: "crayons-field" %>
    </div>
    <div class="crayons-field">
      <%= f.label :profile_image, class: "crayons-field__label" %> (for live notification):
      <%= f.file_field :profile_image, class: "crayons-field" %>
      <img src="<%= @event.profile_image_url %>" style="width: 25%;" alt="event profile image">
    </div>
    <div class="crayons-field">
      <%= f.label :title, class: "crayons-field__label" %>
      <%= f.text_field :title, maxlength: 90, size: 40, required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :host_name, class: "crayons-field__label" %>
      <%= f.text_field :host_name, size: 40, required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :category, class: "crayons-field__label" %>
      <%= f.select :category, ["AMA", "Workshop", "Talk", "Town Hall"], required: true, class: "crayons-select" %>
    </div>
    <div class="crayons-field">
      <%= f.label :starts_at, class: "crayons-field__label" %>
      <fieldset>
      <%= f.datetime_select :starts_at, required: true, include_blank: true, start_year: Time.current.year, end_year: Time.current.year + 2, class: "crayons-select" %> UTC Time Only (4 hours ahead of eastern time)
      </fieldset>
    </div>
    <div class="crayons-field">
      <%= f.label :ends_at, class: "crayons-field__label" %>
      <fieldset>
      <%= f.datetime_select :ends_at, required: true, include_blank: true, start_year: Time.current.year, end_year: Time.current.year + 2, class: "crayons-select" %> UTC Time Only (4 hours ahead of eastern time)
      </fieldset>
    </div>
    <div class="crayons-field">
      <%= f.label :location_name, class: "crayons-field__label" %>
      <%= f.text_field :location_name, required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :location_url, class: "crayons-field__label" %>
      <%= f.text_field :location_url, required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :description_markdown, class: "crayons-field__label" %>
      <%= f.text_area :description_markdown, size: "45x10", required: true, class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= f.label :published, class: "crayons-field__label" %>
      <%= f.check_box :published, class: "crayons-checkbox" %>
    </div>
    <div class="crayons-field">
      <%= f.label :live_now, class: "crayons-field__label" %>
      <%= f.check_box :live_now, class: "crayons-checkbox" %>
    </div>
    <%= f.submit class: "crayons-btn" %>
  <% end %>
</div>

app/views/admin/events/edit.html.erb
<div class="crayons-card p-6 mb-6">
  <h2 class="crayons-title mb-6">Edit Event: <%= @event.title.to_s %></h2>
    <%= render "event_form" %>
</div>

app/views/admin/events/index.html.erb
<header class="flex items-center mb-6">
  <h2 class="crayons-title">Events</h2>
  <%= link_to "New Event", new_admin_event_path, class: "ml-auto crayons-btn crayons-btn--s" %>
</header>
<br>

<div class="crayons-card p-6 pages__table">
  <h3>Upcoming Events</h3>
  <% @events.each do |event| %>
    <% if event.starts_at.future? %>
      <div class="flex py-2 items-center">
        <%= event.title %>
        <% if event.cover_image_url.present? %>
          <img class="mx-auto mt-3" width="40" height="40" src="<%= event.cover_image_url %>" alt="event cover image">
        <% end %>
        <%= link_to "Edit", edit_admin_event_path(event.id), class: "ml-auto crayons-btn crayons-btn--s crayons-btn--secondary" %>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>
<br>

<div class="crayons-card p-6 pages__table">
<h3>Past Events</h3>
  <% @events.each do |event| %>
    <% if !event.starts_at.future? %>
      <div class="flex py-2 items-center">
        <%= event.title %>
        <% if event.cover_image_url.present? %>
          <img class="mx-auto mt-3 justify-content-center" width="40" height="40" src="<%= event.cover_image_url %>" alt="event cover image">
        <% end %>
        <%= link_to "Edit", edit_admin_event_path(event.id), class: "ml-auto crayons-btn crayons-btn--s crayons-btn--secondary" %>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>

app/views/admin/events/new.html.erb
<div class="crayons-card p-6 mb-6">
  <h2 class="crayons-title mb-6">Create New Event</h2>
    <%= render "event_form" %>
</div>