config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper do
    controllers tokens: "oauth/tokens"
  end

  namespace :simplecodingapi do
    post "/signup", to: 'signup#signup'
    post "/login", to: 'signin#login'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    invitations: "invitations",
    passwords: "passwords"
  }

  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    get "/articles", to: "simplecoding_articles#allarticles"
    get "/articles/:id", to: "simplecoding_articles#get_article_by_id"
    get "/articles/slugs/:slug", to: "simplecoding_articles#get_article_by_slug"
    get "/tags", to: "simplecoding_articles#tags"
    get "/tags/:tag", to: "simplecoding_articles#get_by_tag"
    get "/confirm-email", to: "devise/confirmations#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  scope "(/locale/:locale)", defaults: { locale: nil } do
    get "/locale/:locale" => "stories#index"
    require "sidekiq/web"
    require "sidekiq_unique_jobs/web"
    require "sidekiq/cron/web"

    authenticated :user, ->(user) { user.tech_admin? } do
      Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
      Sidekiq::Web.set :sessions, Rails.application.config.session_options
      Sidekiq::Web.class_eval do
        use Rack::Protection, permitted_origins: [URL.url] # resolve Rack Protection HttpOrigin
      end
      mount Sidekiq::Web => "/sidekiq"
      mount FieldTest::Engine, at: "abtests"
    end

    namespace :admin do
      get "/" => "admin_portals#index"

      authenticate :user, ->(user) { user.tech_admin? } do
        mount Blazer::Engine, at: "blazer"

        flipper_ui = Flipper::UI.app(Flipper,
                                     { rack_protection: { except: %i[authenticity_token form_token json_csrf
                                                                     remote_token http_origin session_hijacking] } })
        mount flipper_ui, at: "feature_flags"

        resources :data_update_scripts, only: [:index]
      end

      namespace :users do
        resources :gdpr_delete_requests, only: %i[index destroy]
      end

      resources :articles, only: %i[index show update]
      resources :broadcasts
      resources :buffer_updates, only: %i[create update]
      resources :listings, only: %i[index edit update destroy]
      resources :listing_categories, only: %i[index edit update new create
                                              destroy], path: "listings/categories"

      resources :comments, only: [:index]
      resources :events, only: %i[index create update new edit]
      resources :feedback_messages, only: %i[index show]
      resources :invitations, only: %i[index new create destroy]
      resources :pages, only: %i[index new create edit update destroy]
      resources :mods, only: %i[index update]
      resources :moderator_actions, only: %i[index]
      resources :navigation_links, only: %i[index update create destroy]
      resources :privileged_reactions, only: %i[index]
      resources :permissions, only: %i[index]
      resources :podcasts, only: %i[index edit update destroy] do
        member do
          post :fetch
          post :add_owner
        end
      end

      constraints(->(_request) { FeatureFlag.enabled?(:profile_admin) }) do
        resources :profile_field_groups, only: %i[update create destroy]
        resources :profile_fields, only: %i[index update create destroy]
      end
      resources :reactions, only: [:update]
      resources :response_templates, only: %i[index new edit create update destroy]
      resources :chat_channels, only: %i[index create update destroy] do
        member do
          delete :remove_user
        end
      end
      resources :reports, only: %i[index show], controller: "feedback_messages" do
        collection do
          post "send_email"
          post "create_note"
          post "save_status"
        end
      end
      resources :tags, only: %i[index new create update edit] do
        resource :moderator, only: %i[create destroy], module: "tags"
      end
      resources :users, only: %i[index show edit update] do
        resources :email_messages, only: :show

        member do
          post "banish"
          post "export_data"
          post "full_delete"
          patch "user_status"
          post "merge"
          delete "remove_identity"
          post "send_email"
          post "verify_email_ownership"
          patch "unlock_access"
        end
      end
      resources :organization_memberships, only: %i[update destroy create]
      resources :organizations, only: %i[index show] do
        member do
          patch "update_org_credits"
        end
      end
      resources :sponsorships, only: %i[index edit update new create destroy]
      resources :welcome, only: %i[index create]
      resources :growth, only: %i[index]
      resources :tools, only: %i[index create] do
        collection do
          post "bust_cache"
        end
      end
      resources :webhook_endpoints, only: :index
      resource :config
      resources :badges, only: %i[index edit update new create]
      resources :display_ads, only: %i[index edit update new create destroy]

      resources :html_variants, only: %i[index edit update new create show destroy]
      get "/badges/badge_achievements", to: redirect("/admin/badge_achievements")
      get "/badges/badge_achievements/award_badges", to: redirect("/admin/badge_achievements/award_badges")
      resources :badge_achievements, only: %i[index destroy]
      get "/badge_achievements/award_badges", to: "badge_achievements#award"
      post "/badge_achievements/award_badges", to: "badge_achievements#award_badges"
      resources :secrets, only: %i[index]
      put "secrets", to: "secrets#update"
    end

    namespace :stories, defaults: { format: "json" } do
      resource :feed, only: [:show] do
        get ":timeframe" => "feeds#show"
      end
    end

    namespace :api, defaults: { format: "json" } do
      scope module: :v0,
            constraints: ApiConstraints.new(version: 0, default: true) do
        resources :articles, only: %i[index show create update] do
          collection do
            get "me(/:status)", to: "articles#me", as: :me, constraints: { status: /published|unpublished|all/ }
            get "/:username/:slug", to: "articles#show_by_slug", as: :slug
          end
        end
        resources :comments, only: %i[index show]
        resources :videos, only: [:index]
        resources :podcast_episodes, only: [:index]
        resources :users, only: %i[show] do
          collection do
            get :me
          end
        end
        resources :tags, only: [:index]
        resources :follows, only: [:create] do
          collection do
            get :tags
          end
        end
        namespace :followers do
          get :users
          get :organizations
        end
        resources :readinglist, only: [:index]
        resources :webhooks, only: %i[index create show destroy]

        resources :listings, only: %i[index show create update]
        get "/listings/category/:category", to: "listings#index", as: :listings_category
        get "/analytics/totals", to: "analytics#totals"
        get "/analytics/historical", to: "analytics#historical"
        get "/analytics/past_day", to: "analytics#past_day"
        get "/analytics/referrers", to: "analytics#referrers"

        resources :health_checks, only: [] do
          collection do
            get :app
            get :search
            get :database
            get :cache
          end
        end

        resources :profile_images, only: %i[show], param: :username
        resources :organizations, only: [:show], param: :username do
          resources :users, only: [:index], to: "organizations#users"
          resources :listings, only: [:index], to: "organizations#listings"
          resources :articles, only: [:index], to: "organizations#articles"
        end

        namespace :admin do
          resource :config, only: %i[show update], defaults: { format: :json }
        end
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :chat_channels, only: %i[index show create update]
    resources :chat_channel_memberships, only: %i[index create edit update destroy]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } # internal API
    resources :users, only: %i[update]
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :followed_articles, only: [:index]
    resources :follows, only: %i[show create] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"

app/controllers/admin/listings_controller.rb
module Admin
  class ListingsController < Admin::ApplicationController
    include ListingsToolkit
    ALLOWED_PARAMS = %i[
      published body_markdown title category listing_category_id tag_list action
    ].freeze
    layout "admin"

    def index
      @listings =
        Listing.includes(%i[user listing_category])
          .page(params[:page]).order(bumped_at: :desc).per(50)

      @listings = @listings.published unless include_unpublished?
      @listings = @listings.in_category(params[:filter]) if params[:filter].present?
    end

    def edit
      @listing = Listing.find(params[:id])
    end

    def update
      @listing = Listing.find(params[:id])
      handle_publish_status if listing_params[:published]
      bump_listing(@listing.cost) if listing_params[:action] == "bump"
      update_listing_details
      clear_listings_cache
      flash[:success] = "Listing updated successfully"
      redirect_to edit_admin_listing_path(@listing)
    end

    def destroy
      @listing = Listing.find(params[:id])
      @listing.destroy
      flash[:warning] = "'#{@listing.title}' was destroyed successfully"
      redirect_to admin_listings_path
    end

    private

    private_constant :ALLOWED_PARAMS

    def listing_params
      params.require(:listing).permit(ALLOWED_PARAMS)
    end

    def handle_publish_status
      unpublish_listing if listing_params[:published] == "0"
      publish_listing if listing_params[:published] == "1"
    end

    def include_unpublished?
      params[:include_unpublished] == "1"
    end
  end
end

app/controllers/api/v0/listings_controller.rb
module Api
  module V0
    class ListingsController < ApiController
      include Pundit
      include ListingsToolkit

      # actions `create` and `update` are defined in the module `ListingsToolkit`,
      # we thus silence Rubocop lexical scope filter cop: https://rails.rubystyle.guide/#lexically-scoped-action-filter
      # rubocop:disable Rails/LexicallyScopedActionFilter
      before_action :authenticate_with_api_key_or_current_user!, only: %i[create update]
      before_action :authenticate_with_api_key_or_current_user, only: %i[show]
      before_action :set_cache_control_headers, only: %i[index show]
      before_action :set_listing, only: %i[update]
      skip_before_action :verify_authenticity_token, only: %i[create update]
      # rubocop:enable Rails/LexicallyScopedActionFilter

      # NOTE: since this is used for selecting from the DB, we need to use the
      # actual column name for the listing category, prefixed with classified_.
      ATTRIBUTES_FOR_SERIALIZATION = %i[
        id user_id organization_id title slug body_markdown cached_tag_list
        classified_listing_category_id processed_html published
      ].freeze
      private_constant :ATTRIBUTES_FOR_SERIALIZATION

      def index
        @listings = Listing.published
          .select(ATTRIBUTES_FOR_SERIALIZATION)
          .includes(:user, :organization, :taggings, :listing_category)

        if params[:category].present?
          @listings = @listings.in_category(params[:category])
        end
        @listings = @listings.order(bumped_at: :desc)

        per_page = (params[:per_page] || 30).to_i
        num = [per_page, 100].min
        page = params[:page] || 1
        @listings = @listings.page(page).per(num)

        set_surrogate_key_header Listing.table_key, @listings.map(&:record_key)
      end

      def show
        relation = Listing.published

        # if the user is authenticated we allow them to access
        # their own unpublished listings as well
        relation = relation.union(@user.listings) if @user

        @listing = relation.select(ATTRIBUTES_FOR_SERIALIZATION).find(params[:id])

        set_surrogate_key_header @listing.record_key
      end

      private

      attr_accessor :user

      alias current_user user

      def process_no_credit_left
        msg = "Not enough available credits"
        render json: { error: msg, status: 402 }, status: :payment_required
      end

      def process_successful_draft
        render "show", status: :created
      end

      def process_unsuccessful_draft
        render json: { errors: @listing.errors }, status: :unprocessable_entity
      end

      def process_successful_creation
        render "show", status: :created
      end

      def process_unsuccessful_creation
        render json: { errors: @listing.errors }, status: :unprocessable_entity
      end

      alias process_unsuccessful_update process_unsuccessful_creation

      def process_after_update
        render "show", status: :ok
      end

      def process_after_unpublish
        render "show", status: :ok
      end

      # NOTE: when doing the big listings refactoring we decided not to break
      # this API. Since other code assumes the params will be under listing,
      # we're copying them over.
      def listing_params
        params["listing"] = params["classified_listing"]
        if (category_id = find_category_id(params.dig("listing", "category")))
          params["listing"]["listing_category_id"] = category_id
        end
        super
      end

      def find_category_id(slug)
        return if slug.blank?

        ListingCategory.select(:id).find_by(slug: slug)&.id
      end
    end
  end
end

app/helpers/listing_helper.rb
module ListingHelper
  def select_options_for_categories
    ListingCategory.select(:id, :name, :cost).map do |cl|
      ["#{cl.name} (#{cl.cost} #{'Credit'.pluralize(cl.cost)})", cl.id]
    end
  end

  def categories_for_display
    ListingCategory.pluck(:slug, :name).map do |slug, name|
      { slug: slug, name: name }
    end
  end

  def categories_available
    ListingCategory.all.each_with_object({}) do |cat, h|
      h[cat.slug] = cat.attributes.slice("cost", "name", "rules")
    end.deep_symbolize_keys
  end
end

app/views/admin/listings/edit.html.erb
<header class="mb-6 flex items-center">
  <h2 class="crayons-title mb-4">Edit</h2>

  <div class="ml-auto flex">
    <%= link_to "Remove", url_for(action: :destroy, id: @listing.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger mr-2" %>

    <%= form_with model: [:admin, @listing], method: :patch do |f| %>
      <input type="hidden" name="listing[action]" value="bump" />
      <%= f.submit "Bump Listing ⏫", class: "btn btn-secondary" %>
    <% end %>

    <%= link_to "View", "/listings/#{@listing.category}/#{@listing.slug}", target: "_blank", rel: "noopener", class: "btn btn-primary ml-2" %>

  </div>
</header>

<div class="crayons-card p-6">
  <%= form_with model: [:admin, @listing], method: :patch do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, size: 100, maxlength: 128, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :body_markdown %>
      <%= form.text_area :body_markdown, cols: 40, rows: 15, maxlength: 400, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :tag_list %>
      <i class="fs-s">Comma separated, one space, 8 tags max</i>
      <%= form.text_field :tag_list, value: @listing.cached_tag_list, size: 100, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :listing_category_id %>
      <%= form.select :listing_category_id, select_options_for_categories %>
    </div>
    <div class="form-check">
      <%= form.check_box :published, checked: @listing.published? %>
      <%= form.label :published %>
    </div>
    <%= form.submit "Update Listing", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/listings/index.html.erb
<header class="flex items-center mb-6">
  <h2 class="crayons-title mb-4">Listings</h2>

  <a
    href="<%= admin_listing_categories_path %>"
    aria-label="Listing Categories"
    class="ml-auto crayons-btn">
    Listing Categories
  </a>
</header>

<%= form_tag(admin_listings_path, method: "get", role: "search", class: "crayons-card crayons-card--secondary p-4 flex items-center") do %>
  <div class="mr-4">
    <%= label_tag(:search, "Keyword", class: "mb-0") %>
    <%= text_field_tag(:search, params[:search]) %>
    <% if params[:state].present? %>
      <%= hidden_field_tag(:state, params[:state]) %>
    <% end %>
  </div>

  <div class="mr-4">
    <%= label_tag(:filter, "Category", class: "mb-0") %>
    <%= select_tag(:filter, options_for_select(categories_available.keys, params[:filter]), include_blank: true) %>
  </div>

  <div class="mr-4">
    <%= label_tag(:include_unpublished, "Include unpublished listings", class: "mb-0") %>
    <%= hidden_field_tag(:include_unpublished, 0) %>
    <%= check_box_tag(:include_unpublished, 1, params[:include_unpublished] == "1") %>
  </div>

  <%= submit_tag("Filter") %>
<% end %>

<%= paginate @listings %>

<table class="crayons-table">
  <thead>
    <tr>
      <th scope="col">Title Link</th>
      <th scope="col">User</th>
      <th scope="col">Org</th>
      <th scope="col">Category</th>
      <th scope="col">Cached Tags</th>
      <th scope="col">Published?</th>
      <th scope="col">Last Bumped</th>
    </tr>
  </thead>
  <tbody class="crayons-card">
    <% @listings.each do |listing| %>
      <tr>
        <td><%= link_to listing.title, edit_admin_listing_path(listing.id), rel: "noopener" %></td>
        <td><%= link_to listing.user.username, edit_admin_user_path(listing.user.id) %></td>
        <td><%= link_to listing.organization.name, admin_organization_path(listing.organization_id) if listing.organization_id.present? %></td>
        <td><%= listing.category %></td>
        <td><%= listing.cached_tag_list %></td>
        <td><%= listing.published ? "Yes" : "No" %></td>
        <td><%= listing.bumped_at ? "#{time_ago_in_words(listing.bumped_at)} ago" : "Draft" %></td>
      </tr>
      <tr>
        <td
          class="buffer-cell border-0"
          colspan="7"
          data-controller="buffer"
          data-action="load@window->buffer#autosizeBodyText"
          data-buffer-bg-highlighted-class="bg-highlighted"
          data-buffer-border-highlighted-class="border-highlighted">
          <button
            class="btn btn-secondary"
            data-toggle="collapse"
            data-target="#buffering-area-for-listing-<%= listing.id %>"
            aria-expanded="false"
            aria-controls="buffering-area-for-listing-<%= listing.id %>">
            Share to Buffer
          </button>

          <% if listing.last_buffered.present? %>
            <em class="ml-1">
              Last shared: <%= listing.last_buffered.strftime("%d %B %Y") %>
            </em>
          <% end %>
          <div id="buffering-area-for-listing-<%= listing.id %>" class="collapse buffer-area mt-3">
            <p><strong><%= listing.title %></strong></p>
            <p><%= listing.processed_html&.html_safe %></p>
            <%= form_with url: admin_buffer_updates_path, html: { data: { action: "submit->buffer#highlightElement" } } do %>
              <input type="hidden" name="social_channel" value="listings_twitter" />
              <input type="hidden" name="listing_id" value="<%= listing.id %>" />
              <textarea class="form-control" wrap="hard" name="tweet" maxlength="255" data-buffer-target="bodyText">
              📋 New <%= community_name %> Listing!&#013&#013Category: <%= listing.category %>&#013&#013<%= listing.title %>&#013&#013
                <% if listing.user.twitter_username? %>
                Posted by @<%= listing.user.twitter_username %>
                <% end %>
              </textarea>
              <button class="btn btn-primary mt-2">🐦 Tweet 🐦</button>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @listings %>