config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper do
    controllers tokens: "oauth/tokens"
  end

  namespace :simplecodingapi do
    post "/signup", to: 'signup#signup'
    post "/login", to: 'signin#login'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    invitations: "invitations",
    passwords: "passwords"
  }

  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    get "/articles", to: "simplecoding_articles#allarticles"
    get "/articles/:id", to: "simplecoding_articles#get_article_by_id"
    get "/articles/slugs/:slug", to: "simplecoding_articles#get_article_by_slug"
    get "/tags", to: "simplecoding_articles#tags"
    get "/tags/:tag", to: "simplecoding_articles#get_by_tag"
    get "/confirm-email", to: "devise/confirmations#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  scope "(/locale/:locale)", defaults: { locale: nil } do
    get "/locale/:locale" => "stories#index"
    require "sidekiq/web"
    require "sidekiq_unique_jobs/web"
    require "sidekiq/cron/web"

    authenticated :user, ->(user) { user.tech_admin? } do
      Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
      Sidekiq::Web.set :sessions, Rails.application.config.session_options
      Sidekiq::Web.class_eval do
        use Rack::Protection, permitted_origins: [URL.url] # resolve Rack Protection HttpOrigin
      end
      mount Sidekiq::Web => "/sidekiq"
      mount FieldTest::Engine, at: "abtests"
    end

    namespace :admin do
      get "/" => "admin_portals#index"

      authenticate :user, ->(user) { user.tech_admin? } do
        mount Blazer::Engine, at: "blazer"

        flipper_ui = Flipper::UI.app(Flipper,
                                     { rack_protection: { except: %i[authenticity_token form_token json_csrf
                                                                     remote_token http_origin session_hijacking] } })
        mount flipper_ui, at: "feature_flags"

        resources :data_update_scripts, only: [:index]
      end

      namespace :users do
        resources :gdpr_delete_requests, only: %i[index destroy]
      end

      resources :articles, only: %i[index show update]
      resources :broadcasts
      resources :buffer_updates, only: %i[create update]
      resources :listings, only: %i[index edit update destroy]
      resources :listing_categories, only: %i[index edit update new create
                                              destroy], path: "listings/categories"

      resources :comments, only: [:index]
      resources :events, only: %i[index create update new edit]
      resources :feedback_messages, only: %i[index show]
      resources :invitations, only: %i[index new create destroy]
      resources :pages, only: %i[index new create edit update destroy]
      resources :mods, only: %i[index update]
      resources :moderator_actions, only: %i[index]
      resources :navigation_links, only: %i[index update create destroy]
      resources :privileged_reactions, only: %i[index]
      resources :permissions, only: %i[index]
      resources :podcasts, only: %i[index edit update destroy] do
        member do
          post :fetch
          post :add_owner
        end
      end

      constraints(->(_request) { FeatureFlag.enabled?(:profile_admin) }) do
        resources :profile_field_groups, only: %i[update create destroy]
        resources :profile_fields, only: %i[index update create destroy]
      end
      resources :reactions, only: [:update]
      resources :response_templates, only: %i[index new edit create update destroy]
      resources :chat_channels, only: %i[index create update destroy] do
        member do
          delete :remove_user
        end
      end
      resources :reports, only: %i[index show], controller: "feedback_messages" do
        collection do
          post "send_email"
          post "create_note"
          post "save_status"
        end
      end
      resources :tags, only: %i[index new create update edit] do
        resource :moderator, only: %i[create destroy], module: "tags"
      end
      resources :users, only: %i[index show edit update] do
        resources :email_messages, only: :show

        member do
          post "banish"
          post "export_data"
          post "full_delete"
          patch "user_status"
          post "merge"
          delete "remove_identity"
          post "send_email"
          post "verify_email_ownership"
          patch "unlock_access"
        end
      end
      resources :organization_memberships, only: %i[update destroy create]
      resources :organizations, only: %i[index show] do
        member do
          patch "update_org_credits"
        end
      end
      resources :sponsorships, only: %i[index edit update new create destroy]
      resources :welcome, only: %i[index create]
      resources :growth, only: %i[index]
      resources :tools, only: %i[index create] do
        collection do
          post "bust_cache"
        end
      end
      resources :webhook_endpoints, only: :index
      resource :config
      resources :badges, only: %i[index edit update new create]
      resources :display_ads, only: %i[index edit update new create destroy]

      resources :html_variants, only: %i[index edit update new create show destroy]
      get "/badges/badge_achievements", to: redirect("/admin/badge_achievements")
      get "/badges/badge_achievements/award_badges", to: redirect("/admin/badge_achievements/award_badges")
      resources :badge_achievements, only: %i[index destroy]
      get "/badge_achievements/award_badges", to: "badge_achievements#award"
      post "/badge_achievements/award_badges", to: "badge_achievements#award_badges"
      resources :secrets, only: %i[index]
      put "secrets", to: "secrets#update"
    end

    namespace :stories, defaults: { format: "json" } do
      resource :feed, only: [:show] do
        get ":timeframe" => "feeds#show"
      end
    end

    namespace :api, defaults: { format: "json" } do
      scope module: :v0,
            constraints: ApiConstraints.new(version: 0, default: true) do
        resources :articles, only: %i[index show create update] do
          collection do
            get "me(/:status)", to: "articles#me", as: :me, constraints: { status: /published|unpublished|all/ }
            get "/:username/:slug", to: "articles#show_by_slug", as: :slug
          end
        end
        resources :comments, only: %i[index show]
        resources :videos, only: [:index]
        resources :podcast_episodes, only: [:index]
        resources :users, only: %i[show] do
          collection do
            get :me
          end
        end
        resources :tags, only: [:index]
        resources :follows, only: [:create] do
          collection do
            get :tags
          end
        end
        namespace :followers do
          get :users
          get :organizations
        end
        resources :readinglist, only: [:index]
        resources :webhooks, only: %i[index create show destroy]

        resources :listings, only: %i[index show create update]
        get "/listings/category/:category", to: "listings#index", as: :listings_category
        get "/analytics/totals", to: "analytics#totals"
        get "/analytics/historical", to: "analytics#historical"
        get "/analytics/past_day", to: "analytics#past_day"
        get "/analytics/referrers", to: "analytics#referrers"

        resources :health_checks, only: [] do
          collection do
            get :app
            get :search
            get :database
            get :cache
          end
        end

        resources :profile_images, only: %i[show], param: :username
        resources :organizations, only: [:show], param: :username do
          resources :users, only: [:index], to: "organizations#users"
          resources :listings, only: [:index], to: "organizations#listings"
          resources :articles, only: [:index], to: "organizations#articles"
        end

        namespace :admin do
          resource :config, only: %i[show update], defaults: { format: :json }
        end
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :chat_channels, only: %i[index show create update]
    resources :chat_channel_memberships, only: %i[index create edit update destroy]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } # internal API
    resources :users, only: %i[update]
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :followed_articles, only: [:index]
    resources :follows, only: %i[show create] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"

app/controllers/admin/tags/moderators_controller.rb
module Admin
  module Tags
    class ModeratorsController < Admin::ApplicationController
      def authorization_resource
        Tag
      end

      after_action only: %i[create destroy] do
        Audit::Logger.log(:moderator, current_user, params.dup)
      end

      def create
        user = User.find_by(id: tag_params[:user_id])
        if user&.update(email_tag_mod_newsletter: true)
          TagModerators::Add.call([user.id], [params[:tag_id]])
          flash[:success] = "#{user.username} was added as a tag moderator!"
        else
          flash[:error] = "Error: User ID ##{tag_params[:user_id]} was not found,
          or their account has errors: #{user&.errors_as_sentence}"
        end
        redirect_to edit_admin_tag_path(params[:tag_id])
      end

      def destroy
        user = User.find_by(id: tag_params[:user_id])
        tag = Tag.find_by(id: params[:tag_id])
        if user&.update(email_tag_mod_newsletter: false)
          TagModerators::Remove.call(user, tag)
          flash[:success] = "@#{user.username} - ID ##{user.id} was removed as a tag moderator."
        else
          flash[:error] = "Error: User ID ##{tag_params[:user_id]} was not found,
          or their account has errors: #{user&.errors_as_sentence}"
        end
        redirect_to edit_admin_tag_path(tag.id)
      end

      private

      def tag_params
        params.require(:tag).permit(:user_id)
      end
    end
  end
end

app/controllers/admin/tags_controller.rb
module Admin
  class TagsController < Admin::ApplicationController
    layout "admin"

    before_action :set_default_options, only: %i[index]
    before_action :badges_for_options, only: %i[new create edit update]
    after_action only: [:update] do
      Audit::Logger.log(:moderator, current_user, params.dup)
    end

    def index
      @q = Tag.ransack(params[:q])
      @tags = @q.result.page(params[:page]).per(50)
    end

    def new
      @tag = Tag.new
    end

    def create
      @tag = Tag.new(tag_params)
      @tag.name = params[:tag][:name].downcase

      if @tag.save
        flash[:success] = "Tag has been created!"
        redirect_to edit_admin_tag_path(@tag)
      else
        flash[:danger] = @tag.errors_as_sentence
        render :new
      end
    end

    def edit
      @tag = Tag.find(params[:id])
      @tag_moderators = User.with_role(:tag_moderator, @tag).select(:id, :username)
    end

    def update
      @tag = Tag.find(params[:id])
      if @tag.update(tag_params)
        flash[:success] = "#{@tag.name} tag successfully updated!"
      else
        flash[:error] = "The tag update failed: #{@tag.errors_as_sentence}"
      end
      redirect_to edit_admin_tag_path(@tag.id)
    end

    private

    def set_default_options
      params[:q] = { supported_not_null: "true" } if params[:q].blank?
      params[:q][:s] = "taggings_count desc" if params[:q][:s].blank?
    end

    def badges_for_options
      @badges_for_options = Badge.pluck(:title, :id)
    end

    def tag_params
      allowed_params = %i[
        id supported rules_markdown short_summary pretty_name bg_color_hex
        text_color_hex user_id alias_for badge_id requires_approval
        category social_preview_template wiki_body_markdown submission_template
      ]
      params.require(:tag).permit(allowed_params)
    end
  end
end

app/controllers/api/v0/tags_controller.rb
module Api
  module V0
    class TagsController < ApiController
      before_action :set_cache_control_headers, only: %i[index]

      ATTRIBUTES_FOR_SERIALIZATION = %i[id name bg_color_hex text_color_hex].freeze
      private_constant :ATTRIBUTES_FOR_SERIALIZATION

      def index
        page = params[:page]
        per_page = (params[:per_page] || 10).to_i
        num = [per_page, 1000].min

        @tags = Tag.select(ATTRIBUTES_FOR_SERIALIZATION)
          .order(taggings_count: :desc)
          .page(page).per(num)

        set_surrogate_key_header Tag.table_key, @tags.map(&:record_key)
      end
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_cache_control_headers, only: %i[index onboarding]
  before_action :authenticate_user!, only: %i[edit update]
  after_action :verify_authorized

  ATTRIBUTES_FOR_SERIALIZATION = %i[id name bg_color_hex text_color_hex].freeze

  def index
    skip_authorization
    @tags_index = true
    @tags = Tag.includes(:sponsorship).order(hotness_score: :desc).limit(100)
  end

  def edit
    @tag = Tag.find_by!(name: params[:tag])
    authorize @tag
  end

  def update
    @tag = Tag.find(params[:id])
    authorize @tag
    if @tag.errors.messages.blank? && @tag.update(tag_params)
      flash[:success] = "Tag successfully updated! 👍 "
      redirect_to "/t/#{URI.parse(@tag.name).path}/edit"
    else
      flash[:error] = @tag.errors.full_messages
      render :edit
    end
  end

  def admin
    tag = Tag.find_by!(name: params[:tag])
    authorize tag
    redirect_to "/admin/tags/#{tag.id}/edit"
  end

  def onboarding
    skip_authorization

    @tags = Tag.where(name: SiteConfig.suggested_tags)
      .select(ATTRIBUTES_FOR_SERIALIZATION)

    set_surrogate_key_header Tag.table_key, @tags.map(&:record_key)
  end

  private

  def convert_empty_string_to_nil
    # nil plays nicely with our hex colors, whereas empty string doesn't
    params[:tag][:text_color_hex] = nil if params[:tag][:text_color_hex] == ""
    params[:tag][:bg_color_hex] = nil if params[:tag][:bg_color_hex] == ""
  end

  def tag_params
    accessible = %i[
      wiki_body_markdown
      rules_markdown
      short_summary
      pretty_name
      bg_color_hex
      text_color_hex
    ]
    convert_empty_string_to_nil
    params.require(:tag).permit(accessible)
  end

  private_constant :ATTRIBUTES_FOR_SERIALIZATION
end

app/views/tags/_liquid.html.erb
<div class="ltag__tag ltag__tag__id__<%= tag.id %>" style="border-color:<%= dark_color %>;box-shadow: 3px 3px 0px <%= dark_color %>;">
  <style>
    .ltag__tag__id__<%= tag.id %> .follow-action-button{
      background-color: <%= tag.bg_color_hex %> !important;
      color: <%= tag.text_color_hex %> !important;
      border-color: <%= tag.bg_color_hex.to_s.casecmp("#ffffff").zero? ? tag.text_color_hex : tag.bg_color_hex %> !important;
    }
  </style>
    <div class="ltag__tag__content">
      <h2>#<a href="/t/<%= tag.name %>" class="ltag__tag__link"><%= tag.name %></a> <%= follow_btn %></h2>
      <div class="ltag__tag__summary">
        <%= tag.short_summary %>
      </div>
    </div>
</div>

app/views/tags/edit.html.erb
<% title "Edit #{@tag.name}" %>

<style>
  .widget header {
    color: <%= Color::CompareHex.new([@tag.bg_color_hex || "#0000000", @tag.text_color_hex || "#ffffff"]).brightness(0.8) %>
  }

  .slanty-accent {
    background-color: <%= Color::CompareHex.new([@tag.bg_color_hex || "#ffffff"]).accent %>
  }

  .tag-edit-tag {
    text-align: center;
    color: <%= @tag.text_color_hex %>;
  }
</style>
<br>
<br>
<br>
<div class="user-profile-header tag-header" style="background-color:<%= @tag.bg_color_hex %>;color:<%= @tag.text_color_hex %>;">
  <div class="slanty-accent"></div>
  <div class="tag-or-query-header-container tag-edit-tag">
    <h1> Editing:
      <a href="/t/<%= @tag.name %>" style="color: <%= @tag.text_color_hex %>;text-decoration: underline;"><%= @tag.name %></a>
    </h1>
    <p>
      <code style="background-color: #D2D2D2; color: black; padding: 5px; border-radius: 5px;">#<%= @tag.name %></code> is the name of the tag used in Markdown.
    </p>
  </div>
</div>
<%= form_tag("/tag/#{@tag.id}", method: :patch, class: "tag-edit-form") do %>
  <div class="tag-edit-container">
    <% if flash[:success] %>
      <p class="tag-edit-flash-success">
        <%= flash[:success] %>
      </p>
    <% elsif flash[:error] %>
      <ul class="tag-edit-flash-error">
        <% flash[:error].each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <h4>
      <a target="_blank" rel="noopener" href="https://thepracticaldev.s3.amazonaws.com/i/cc8vz48djnhty6c31jog.png">
        Click here to see an example of attributes.
      </a>
    </h4>
    <div class="tag-form-field">
      <%= label_tag :pretty_name %>
      <br>
      <%= text_field_tag "tag[pretty_name]", @tag.pretty_name, placeholder: "This is the name at the top of the show page.", class: "tag-form-text-field" %>
    </div>
    <div class="tag-form-field">
      <%= label_tag :bg_color_hex %>
      <br>
      <%= color_field_tag "tag[bg_color_hex]", @tag.bg_color_hex, placeholder: "Click for color picker", class: "tag-form-text-field" %>
    </div>
    <div class="tag-form-field">
      <%= label_tag :text_color_hex %>
      <br>
      <%= color_field_tag "tag[text_color_hex]", @tag.text_color_hex, placeholder: "Click for color picker", class: "tag-form-text-field" %>
    </div>
    <div class="tag-form-field">
      <%= label_tag :short_summary %>
      <br>
      <%= text_area_tag "tag[short_summary]", @tag.short_summary, placeholder: "Brief overview of what this tag is all about.", class: "tag-form-text-field tag-area-text" %>
    </div>
    <div class="tag-form-field">
      <%= label_tag :wiki_body_markdown %>
      <br>
      <%= text_area_tag "tag[wiki_body_markdown]", @tag.wiki_body_markdown, placeholder: "This is an 'about' section. Feel free to add an FAQ, additional resources, etc.", class: "tag-form-text-field tag-area-text" %>
    </div>
    <div class="tag-form-field">
      <%= label_tag :rules_markdown %>
      <br>
      <%= text_area_tag "tag[rules_markdown]", @tag.rules_markdown, placeholder: "Optional - Can be used for challenges, i.e. submission guidelines.", class: "tag-form-text-field tag-area-text" %>
    </div>
    <div class="tag-form-field">
      <%= submit_tag "SAVE CHANGES", class: "tag-edit-submit" %>
    </div>
  </div>
<% end %>

<% if current_user.has_role?(:super_admin) || current_user.has_role?(:admin) %>
  <center>
    <h1><a href="/admin/tags/<%= @tag.id %>" data-no-instant><%= @tag.name %> admin</a></h1>
    <br />
    <br />
    <br />
  </center>
<% end %>

app/views/tags/index.html.erb
<% title "Tags on #{community_name}" %>

<%= content_for :page_meta do %>
  <link rel="canonical" href="<%= app_url("/tags") %>" />
  <meta name="description" content="Tags to follow on <%= community_name %>">
  <%= meta_keywords_default %>

  <meta property="og:type" content="article" />
  <meta property="og:url" content="<%= app_url("/tags") %>" />
  <meta property="og:title" content="Tags to follow on <%= community_name %>" />
  <meta property="og:image" content="<%= SiteConfig.main_social_image %>" />
  <meta property="og:description" content="<%= community_name %> is great!" />
  <meta property="og:site_name" content="<%= community_name %>" />

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@<%= SiteConfig.social_media_handles["twitter"] %>">
  <meta name="twitter:title" content="About <%= community_name %>">
  <meta name="twitter:description" content="<%= community_name %> is great!">
  <meta name="twitter:image:src" content="<%= SiteConfig.main_social_image %>">
<% end %>

<div class="crayons-layout crayons-layout--1-col">
  <header class="px-2 m:px-0">
    <h1>Top tags</h1>
  </header>

  <div class="grid gap-2 m:gap-4 l:gap-6 m:grid-cols-2 l:grid-cols-3 px-2 m:px-0">
    <% @tags.each do |tag| %>
      <% color = Color::CompareHex.new([tag.bg_color_hex || "#0000000", tag.text_color_hex || "#ffffff"]).brightness(0.8) %>
      <div class="tag-card crayons-card branded-4 p-4 m:p-6 m:pt-4 flex flex-col relative" style="border-top-color: <%= color %>; ">
        <h3 class="crayons-tag crayons-tag--l mb-2">
          <a href="/t/<%= tag.name %>" class="crayons-link">
            <span class="crayons-tag__prefix">#</span><%= tag.name %>
          </a>
        </h3>
        <% if tag.short_summary.present? %>
          <p class="mb-2 color-base-70 truncate-at-3"><%= sanitize tag.short_summary %></p>
        <% end %>
        <p class="mb-3 fs-s color-base-60">
          <%= pluralize tag.taggings_count, "post" %> published
          <% if tag.sponsorship && tag.sponsorship.status == "live" && tag.sponsorship.expires_at > Time.current %>
          | Sponsored by <%= tag.sponsorship.organization.name %> ❤️
          <% end %>
        </p>

        <% if tag %>
          <div class="mt-auto">
            <button
              class="crayons-btn crayons-btn--secondary follow-action-button"
              data-info='{"id":<%= tag.id %>,"className":"Tag", "followStyle":"secondary"}'>
              Follow
            </button>
          </div>
        <% end %>

        <% if tag.badge_id && tag.badge %>
          <img src="<%= optimized_image_url(tag.badge.badge_image_url, width: 180) %>" style="width: 64px; height: 64px; transform: rotate(<%= -25 + (tag.id.digits.first * 5) %>deg);" class="right-1 bottom-1 absolute" alt="" />
        <% end %>
      </div>
    <% end %>
  </div>
</div>